
CREATE TABLE VENDOR (
		ID INTEGER NOT NULL,

		VENDORCODE INTEGER NOT NULL,

		DESCRIPTION VARCHAR(255) NOT NULL,

		VENDORNAME VARCHAR(255) NOT NULL,

		-- address
    VENDORADDRESS VARCHAR(255) NOT NULL
	);

CREATE UNIQUE INDEX PRIMARY_KEY_4 ON VENDOR (ID ASC);

ALTER TABLE VENDOR ADD CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID);
